{{- $fullname := include "service.fullname" . -}}
{{- $name := include "service.name" . -}}
{{- $chart := include "service.chart" . -}}
{{- $root := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ $root.Values.configName | default "designs-aggregate" }}.{{ $root.Release.Revision | default "1" }}'
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
data:
  config.json: |
    {
      "host_port": "8080",

      "server_keystore_path": "/etc/keystore_server.jks",
      "server_keystore_secret": "${KEYSTORE_SECRET}",

      "jwt_keystore_path": "/etc/keystore_auth.jceks",
      "jwt_keystore_type": "jceks",
      "jwt_keystore_secret": "${KEYSTORE_SECRET}",

      "origin_pattern": "https://{{ $root.Values.clientDomain | default "localhost" }}(:[0-9]+)?",

      "cassandra_cluster": {{ $root.Values.datacenter | default "datacenter1" | quote }},
      "cassandra_keyspace": {{ $root.Values.cassandraKeyspace | default "designs_aggregate" | quote }},
      "cassandra_username": "${DATABASE_USERNAME}",
      "cassandra_password": "${DATABASE_PASSWORD}",
      "cassandra_contactPoints": {{ $root.Values.cassandraContactPoints | default "cassandra.platform" | quote }},
      "cassandra_port": {{ $root.Values.cassandraPort | default 9042 | quote }},

      "kafka_bootstrap_servers": {{ $root.Values.kafkaServers | default "kafka.platform:9094" | quote }},
      "kafka_group_id": {{ $root.Values.kafkaGroupId | default "designs-aggregate" | quote }},
      "message_source": {{ $root.Values.messageSource | default "service-designs" | quote }},
      "events_topic": {{ $root.Values.eventsTopic | default "events" | quote }},
      "cancel_topic": {{ $root.Values.cancelTopic | default "cancel" | quote }},
      "buffer_topic": {{ $root.Values.bufferTopic | default "buffer" | quote }},
      "render_topic_prefix": {{ $root.Values.renderTopicPrefix | default "render" | quote }}
    }
