{{- $fullname := include "service.fullname" . -}}
{{- $name := include "service.name" . -}}
{{- $chart := include "service.chart" . -}}
{{- $root := . }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ $root.Values.secretName | default "minio" }}.{{ $root.Release.Revision | default "1" }}'
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
data:
  MINIO_ROOT_USER: {{ $root.Values.minioRootUser | default "admin" }}
  MINIO_ROOT_PASSWORD: {{ $root.Values.minioRootPassword | default "password" }}
