{{- $fullname := include "service.fullname" . -}}
{{- $name := include "service.name" . -}}
{{- $chart := include "service.chart" . -}}
{{- $root := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $root.Values.name | default "accounts" | quote }}
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
data:
  config.json: |
    {
      "host_port": "8080",

      "server_keystore_path": "/etc/keystore_server.jks",
      "server_keystore_secret": "${KEYSTORE_SECRET}",

      "jwt_keystore_path": "/etc/keystore_auth.jceks",
      "jwt_keystore_type": "jceks",
      "jwt_keystore_secret": "${KEYSTORE_SECRET}",

      "origin_pattern": "https://{{ $root.Values.clientDomain | default "localhost" }}(:[0-9]+)?",

      "jdbc_url": "jdbc:mysql://mysql:3306/accounts?useSSL=false&allowPublicKeyRetrieval=true&nullNamePatternMatchesAll=true",
      "jdbc_driver": "com.mysql.cj.jdbc.Driver",
      "jdbc_username": "${DATABASE_USERNAME}",
      "jdbc_password": "${DATABASE_PASSWORD}",
      "jdbc_max_pool_size": "200",
      "jdbc_min_pool_size": "20",

      "graphite_reporter_enabled": "false",
      "graphite_host": "graphite",
      "graphite_port": "2003"
    }