DROP DATABASE IF EXISTS designs;
CREATE DATABASE designs;

CREATE USER IF NOT EXISTS admin IDENTIFIED BY 'password' PASSWORD EXPIRE NEVER;
CREATE USER IF NOT EXISTS verticle IDENTIFIED BY 'password' PASSWORD EXPIRE NEVER;
GRANT SELECT, INSERT, UPDATE, DELETE ON admin.* TO verticle;
GRANT SELECT, INSERT, UPDATE, DELETE ON designs.* TO verticle;

USE designs;

CREATE TABLE IF NOT EXISTS DESIGN (
    DESIGN_UUID VARCHAR(36) PRIMARY KEY,
    DESIGN_DATA JSON NOT NULL,
    DESIGN_CHECKSUM VARCHAR(100) NOT NULL,
    DESIGN_CREATED TIMESTAMP NOT NULL,
    DESIGN_UPDATED TIMESTAMP NOT NULL,
    DESIGN_PUBLISHED TIMESTAMP
);

CREATE TABLE IF NOT EXISTS VERSION (
    DESIGN_CHECKSUM VARCHAR(100) PRIMARY KEY,
    DESIGN_DATA JSON NOT NULL,
    VERSION_CREATED TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS TILE (
    DESIGN_CHECKSUM VARCHAR(100) PRIMARY KEY,
    TILE_LEVEL INTEGER(10) PRIMARY KEY,
    TILE_ROW INTEGER(10) PRIMARY KEY,
    TILE_COL INTEGER(10) PRIMARY KEY,
    TILE_STATUS VARCHAR(32),
    TILE_LOCATION VARCHAR(512) NOT NULL,
    TILE_CREATED TIMESTAMP NOT NULL,
    TILE_UPDATED TIMESTAMP NOT NULL
);

FLUSH PRIVILEGES;
