openapi: 3.0.1
info:
  title: Designs Aggregate API
  description: API contract of service Designs Aggregate
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost
tags:
  - name: designs
    description: Everything about processing events and aggregates
paths:
  /apidocs:
    get:
      operationId: apidocs
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /health:
    get:
      operationId: health
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /metrics:
    get:
      operationId: metrics
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
