openapi: 3.0.1
info:
  title: Designs Aggregate API
  description: API contract of service Designs Aggregate
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://localhost/v1
tags:
  - name: designs
    description: Everything about processing events and aggregates
paths:
  {}
