{{- $fullname := include "service.fullname" . -}}
{{- $name := include "service.name" . -}}
{{- $chart := include "service.chart" . -}}
{{- $root := . }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ $root.Values.secretName | default "postgres" }}.{{ $root.Release.Revision | default "1" }}'
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
data:
  POSTGRES_USER: {{ $root.Values.postgresUser | default "admin" }}
  POSTGRES_PASSWORD: {{ $root.Values.postgresPassword | default "password" }}
  init.sql: |
    SELECT 'CREATE USER {{ $root.Values.pactbrokerUser | default "pactbrokeruser" }} WITH PASSWORD ''{{ $root.Values.pactbrokerPassword | default "password" }}''' WHERE NOT EXISTS (SELECT FROM pg_user WHERE usename = '{{ $root.Values.pactbrokerUser | default "pactbrokeruser" }}')\gexec
    SELECT 'CREATE DATABASE pactbroker WITH OWNER {{ $root.Values.pactbrokerUser | default "pactbrokeruser" }}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'pactbroker')\gexec
    GRANT ALL PRIVILEGES ON DATABASE pactbroker TO {{ $root.Values.pactbrokerUser | default "pactbrokeruser" }};
