{{- $fullname := include "service.fullname" . -}}
{{- $name := include "service.name" . -}}
{{- $chart := include "service.chart" . -}}
{{- $root := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $root.Values.name | default "frontend" | quote }}
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
data:
  config.json: |
    {
      "client_web_url": {{ $root.Values.clientWebUrl | default "https://localhost:8081" | quote }},
      "client_api_url": {{ $root.Values.clientApiUrl | default "https://localhost:8081" | quote }},
      "server_api_url": "https://gateway:8080"
    }