openapi: 3.0.1
info:
  title: Designs Notify API
  description: API contract of service Designs Notify
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost
tags:
  - name: designs
    description: Everything about receiving notifications about designs
paths:
  /apidocs:
    get:
      operationId: apidocs
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /health:
    get:
      operationId: health
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /metrics:
    get:
      operationId: metrics
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /v1/designs/watch:
    options:
      operationId: watchDesignsOptions
      responses:
        204:
          description: No Content
    get:
      tags:
        - designs
      summary: Receive events about designs
      operationId: watchDesigns
      parameters:
        - name: revision
          in: query
          description: initial revision
          required: true
          schema:
            type: string
        - name: designId
          in: query
          description: uuid of the design to watch
          required: false
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Started watching
          content:
            {}
components:
  schemas:
    {}
