apiVersion: v1
kind: Service
metadata:
  name: accounts-service
  namespace: default
  labels:
    app: accounts-service
spec:
  ports:
    - port: 3002
      name: accounts-service
  selector:
    app: accounts-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: accounts-service
  namespace: default
  labels:
    app: accounts-service
spec:
  template:
    metadata:
      name: accounts-service
      namespace: default
      labels:
        app: accounts-service
    spec:
      containers:
      - image: docker/accounts-service:1.0.0
        name: accounts-service
        volumeMounts:
        - name: accounts-service-config
          mountPath: /config
          readOnly: true
        - name: keystores
          mountPath: /keystores
          readOnly: true
      volumes:
      - name: accounts-service-config
        secret:
          secretName: accounts-service-config
      - name: keystores
        secret:
          secretName: keystores
