openapi: 3.0.1
info:
  title: Designs Render API
  description: API contract of service Designs Render
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost
tags:
  - name: designs
    description: Everything about validating designs and parsing files
paths:
  /apidocs:
    get:
      operationId: apidocs
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /health:
    get:
      operationId: health
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /metrics:
    get:
      operationId: metrics
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /v1/designs/validate:
    options:
      operationId: validateDesignOptions
      responses:
        204:
          description: No Content
    post:
      tags:
        - designs
        - validate
      summary: Validate a design
      operationId: validateDesign
      requestBody:
        description: Design data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Design'
      responses:
        200:
          description: Validation status and errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateDesignResponse'
        400:
          description: Invalid request
        401:
          description: Missing authentication
        403:
          description: User not authorized
#      security:
#        - design_auth:
#            - admin
  /v1/designs/download:
    options:
      operationId: downloadDesignOptions
      responses:
        204:
          description: No Content
    post:
      tags:
        - designs
        - download
      summary: Return design as file
      operationId: downloadDesign
      requestBody:
        description: Design data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Design'
      responses:
        200:
          description: Content of the file
          content:
            application/zip:
              schema:
                type: string
                format: binary
        400:
          description: Invalid request
        401:
          description: Missing authentication
        403:
          description: User not authorized
  #      security:
  #        - design_auth:
  #            - admin
  /v1/designs/upload:
    options:
      operationId: uploadDesignOptions
      responses:
        204:
          description: No Content
    post:
      tags:
        - designs
        - upload
      summary: Return design from file
      operationId: uploadDesign
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: Design and validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadDesignResponse'
        400:
          description: Invalid request
        401:
          description: Missing authentication
        403:
          description: User not authorized
#      security:
#        - design_auth:
#            - admin
  /v1/designs/render:
    options:
      operationId: renderDesignOptions
      responses:
        204:
          description: No Content
    post:
      tags:
        - designs
        - render
      summary: Render a design
      operationId: renderDesign
      requestBody:
        description: Design data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Design'
      responses:
        200:
          description: Render result and errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderDesignResponse'
        400:
          description: Invalid request
        401:
          description: Missing authentication
        403:
          description: User not authorized
#      security:
#        - design_auth:
#            - admin
  /v1/designs/image:
    options:
      operationId: getImageOptions
      responses:
        204:
          description: No Content
    get:
      tags:
        - designs
        - get
      summary: Get rendered image
      operationId: getImage
      responses:
        200:
          description: Image data
          content:
            image/png:
              {}
        400:
          description: Invalid request
        401:
          description: Missing authentication
        403:
          description: User not authorized
        404:
          description: Tile not found
#      security:
#        - design_auth:
#            - admin
components:
  schemas:
    Design:
      type: object
      properties:
        manifest:
          type: string
        metadata:
          type: string
        script:
          type: string
      required:
        - manifest
        - metadata
        - script
    ValidateDesignResponse:
      type: object
      properties:
        status:
          type: string
          enum: [ACCEPTED, REJECTED]
        errors:
          type: array
          items:
            type: string
      required:
        - status
        - errors
    UploadDesignResponse:
      type: object
      properties:
        manifest:
          type: string
        metadata:
          type: string
        script:
          type: string
      required:
        - manifest
        - metadata
        - script
    RenderDesignResponse:
      type: object
      properties:
        checksum:
          type: string
        errors:
          type: array
          items:
            type: string
      required:
        - checksum
        - errors
#  securitySchemes:
#    design_auth:
#      type: oauth2
#      flows:
#        implicit:
#          authorizationUrl: https://localhost:8081/auth/signin
#          scopes:
#            anonymous: user not logged
#            admin: user logged as admin
#            guest: user logged as guest
#            platform: platform token
