openapi: 3.0.1
info:
  title: Designs Render API
  description: API contract of service Designs Render
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://localhost/v1
tags:
  - name: designs
    description: Everything about validating designs and parsing files
paths:
  /designs/validate:
    post:
      tags:
        - designs
        - validate
      summary: Validate a design
      operationId: validateDesign
      requestBody:
        description: Design data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Design'
      responses:
        200:
          description: Validation status and errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateDesignResponse'
        400:
          description: Invalid request
          content: {}
        401:
          description: Missing authentication
          content: {}
        403:
          description: User not authorized
          content: {}
#      security:
#        - design_auth:
#            - admin
  /designs/download:
    post:
      tags:
        - designs
        - download
      summary: Return design as file
      operationId: downloadDesign
      requestBody:
        description: Design data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Design'
      responses:
        200:
          description: Content of the file
          content:
            application/zip:
              schema:
                type: string
                format: binary
        400:
          description: Invalid request
          content: {}
        401:
          description: Missing authentication
          content: {}
        403:
          description: User not authorized
          content: {}
  #      security:
  #        - design_auth:
  #            - admin
  /designs/upload:
    post:
      tags:
        - designs
        - upload
      summary: Return design from file
      operationId: uploadDesign
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: Design and validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadDesignResponse'
        400:
          description: Invalid request
          content: {}
        401:
          description: Missing authentication
          content: {}
        403:
          description: User not authorized
          content: {}
#      security:
#        - design_auth:
#            - admin
components:
  schemas:
    Design:
      type: object
      properties:
        manifest:
          type: string
        metadata:
          type: string
        script:
          type: string
      required:
        - manifest
        - metadata
        - script
    ValidateDesignResponse:
      type: object
      properties:
        status:
          type: string
          enum: [ACCEPTED, REJECTED]
        errors:
          type: array
          items:
            type: string
      required:
        - status
        - errors
    UploadDesignResponse:
      type: object
      properties:
        manifest:
          type: string
        metadata:
          type: string
        script:
          type: string
      required:
        - manifest
        - metadata
        - script
#  securitySchemes:
#    design_auth:
#      type: oauth2
#      flows:
#        implicit:
#          authorizationUrl: https://localhost:8081/auth/signin
#          scopes:
#            anonymous: user not logged
#            admin: user logged as admin
#            guest: user logged as guest
#            platform: platform token
