version: '3.4'
services:
  shop-weblet-root:
    labels:
        service: shop-weblet-root
    image: ${SHOP_WEBLET_ADMIN_IMAGE}
    volumes:
      - storage:/data
    logging:
      options:
        labels: "service"
    ports:
      - target: 8080
        published: 48080
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
          - node.labels.public == false
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
    secrets:
      - source: weblet_root_conf
        target: /config/config.json
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: ca_cert
        target: /secrets/ca_cert.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: server_key
        target: /secrets/server_key.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: server_cert
        target: /secrets/server_cert.pem
        uid: '1000'
        gid: '1000'
        mode: 0440
networks:
  default:
    external:
      name: services
volumes:
    storage:
secrets:
  weblet_root_conf:
    file: ${ENVIRONMENT_SECRETS_PATH}/services/weblet-root.json
  ca_cert:
    file: ${ENVIRONMENT_SECRETS_PATH}/nginx/ca_cert.pem
  server_key:
    file: ${ENVIRONMENT_SECRETS_PATH}/nginx/server_key.pem
  server_cert:
    file: ${ENVIRONMENT_SECRETS_PATH}/nginx/server_cert.pem
