CREATE USER IF NOT EXISTS 'liquibase' IDENTIFIED BY 'password' PASSWORD EXPIRE NEVER;
CREATE USER IF NOT EXISTS 'verticle' IDENTIFIED BY 'password' PASSWORD EXPIRE NEVER;
GRANT ALL ON `designs`.* TO 'liquibase';
GRANT SELECT, INSERT, UPDATE, DELETE ON `designs`.* TO 'verticle';
FLUSH PRIVILEGES;
