{{- $fullname := include "service.fullname" . -}}
{{- $name := include "service.name" . -}}
{{- $chart := include "service.chart" . -}}
{{- $root := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ $root.Values.configName | default "accounts" }}.{{ $root.Release.Revision | default "1" }}'
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
data:
  config.json: |
    {
      "host_port": "8080",

      "jwt_keystore_path": "/etc/keystore_auth.jceks",
      "jwt_keystore_type": "jceks",
      "jwt_keystore_secret": "${KEYSTORE_SECRET}",

      "origin_pattern": "https://{{ $root.Values.clientDomain | default "localhost" }}(:[0-9]+)?",

      "jdbc_url": "jdbc:mysql://{{ $root.Values.databaseHost | default "mysql.platform" }}:{{ $root.Values.databasePort | default "3306" }}/{{ $root.Values.databaseName | default "accounts" }}?useSSL=false&allowPublicKeyRetrieval=true&nullNamePatternMatchesAll=true&generateSimpleParameterMetadata=true",
      "jdbc_driver": "com.mysql.cj.jdbc.Driver",
      "jdbc_username": "${DATABASE_USERNAME}",
      "jdbc_password": "${DATABASE_PASSWORD}",
      "jdbc_max_pool_size": {{ $root.Values.databaseMaxPoolSize | default "200" | quote }},
      "jdbc_min_pool_size": {{ $root.Values.databaseMinPoolSize | default "20" | quote }}
    }