export const SET_CONFIG = 'SET_CONFIG';
export const SET_ACCOUNT = 'SET_ACCOUNT';

export const SET_DESIGN = 'SET_DESIGN';
export const SET_DESIGNS = 'SET_DESIGNS';

export const SHOW_UPDATE_DESIGN = 'SHOW_UPDATE_DESIGN';
export const HIDE_UPDATE_DESIGN = 'HIDE_UPDATE_DESIGN';

export const SHOW_CREATE_DESIGN = 'SHOW_CREATE_DESIGN';
export const HIDE_CREATE_DESIGN = 'HIDE_CREATE_DESIGN';

export const SHOW_DELETE_DESIGNS = 'SHOW_DELETE_DESIGNS';
export const HIDE_DELETE_DESIGNS = 'HIDE_DELETE_DESIGNS';

export const SET_ORDER = 'SET_ORDER';
export const SET_PAGE = 'SET_PAGE';
export const SET_ROWS_PER_PAGE = 'SET_ROWS_PER_PAGE';
export const SET_SELECTED = 'SET_SELECTED';
