export const CONFIG_LOAD = 'CONFIG_LOAD'
export const CONFIG_LOAD_SUCCESS = 'CONFIG_LOAD_SUCCESS'
export const CONFIG_LOAD_FAILURE = 'CONFIG_LOAD_FAILURE'

export const ACCOUNT_LOAD = 'ACCOUNT_LOAD'
export const ACCOUNT_LOAD_SUCCESS = 'ACCOUNT_LOAD_SUCCESS'
export const ACCOUNT_LOAD_FAILURE = 'ACCOUNT_LOAD_FAILURE'

export const DESIGN_LOAD = 'DESIGN_LOAD'
export const DESIGN_LOAD_SUCCESS = 'DESIGN_LOAD_SUCCESS'
export const DESIGN_LOAD_FAILURE = 'DESIGN_LOAD_FAILURE'

export const DESIGNS_LOAD = 'DESIGNS_LOAD'
export const DESIGNS_LOAD_SUCCESS = 'DESIGNS_LOAD_SUCCESS'
export const DESIGNS_LOAD_FAILURE = 'DESIGNS_LOAD_FAILURE'

export const SHOW_UPDATE_DESIGN = 'SHOW_UPDATE_DESIGN'
export const HIDE_UPDATE_DESIGN = 'HIDE_UPDATE_DESIGN'

export const SHOW_CREATE_DESIGN = 'SHOW_CREATE_DESIGN'
export const HIDE_CREATE_DESIGN = 'HIDE_CREATE_DESIGN'

export const SHOW_DELETE_DESIGNS = 'SHOW_DELETE_DESIGNS'
export const HIDE_DELETE_DESIGNS = 'HIDE_DELETE_DESIGNS'

export const DESIGNS_SORTING_UPDATE = 'DESIGNS_SORTING_UPDATE'
export const DESIGNS_SELECTION_UPDATE = 'DESIGNS_SELECTION_UPDATE'
export const DESIGNS_PAGINATION_UPDATE = 'DESIGNS_PAGINATION_UPDATE'
