export const SET_CONFIG = 'SET_CONFIG';
export const SET_ACCOUNT = 'SET_ACCOUNT';

export const SET_DESIGNS = 'SET_DESIGNS';
export const SHOW_CREATE_DESIGN = 'SHOW_CREATE_DESIGN';
export const HIDE_CREATE_DESIGN = 'HIDE_CREATE_DESIGN';
export const CONFIRM_CREATE_DESIGN = 'CONFIRM_CREATE_DESIGN';
export const SHOW_DELETE_DESIGN = 'SHOW_DELETE_DESIGN';
export const HIDE_DELETE_DESIGN = 'HIDE_DELETE_DESIGN';
export const CONFIRM_DELETE_DESIGN = 'CONFIRM_DELETE_DESIGN';
export const SET_PAGE = 'SET_PAGE';
export const SET_ROWS_PER_PAGE = 'SET_ROWS_PER_PAGE';

export const SET_DESIGN = 'SET_DESIGN';
