openapi: 3.0.1
info:
  title: Accounts API
  description: API contract of service Accounts
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost
tags:
  - name: accounts
    description: Everything about accounts
paths:
  /apidocs:
    get:
      operationId: apidocs
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /health:
    get:
      operationId: health
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /metrics:
    get:
      operationId: metrics
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /v1/accounts/me:
    options:
      operationId: selfAccountOptions
      responses:
        204:
          description: No Content
    get:
      tags:
        - accounts
      summary: Load account of logged user
      operationId: loadSelfAccount
      responses:
        200:
          description: Return account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        401:
          description: Missing authentication
        403:
          description: User not authorized
        404:
          description: Account not found
#      security:
#        - account_auth:
#            - admin
#            - guest
  /v1/accounts/{accountId}:
    options:
      operationId: accountOptions
      responses:
        204:
          description: No Content
    get:
      tags:
        - accounts
      summary: Load an account
      operationId: loadAccount
      parameters:
        - name: accountId
          in: path
          description: uuid of account to return
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Return account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        400:
          description: Invalid uuid supplied
        401:
          description: Missing authentication
        403:
          description: User not authorized
        404:
          description: Account not found
#      security:
#        - account_auth:
#            - admin
#            - platform
    delete:
      tags:
        - accounts
      summary: Delete an account
      operationId: deleteAccount
      parameters:
        - name: accountId
          in: path
          description: uuid of account to delete
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Account deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteAccountResponse'
        400:
          description: Invalid uuid supplied
        401:
          description: Missing authentication
        403:
          description: User not authorized
#      security:
#        - account_auth:
#            - admin
  /v1/accounts:
    options:
      operationId: accountsOptions
      responses:
        204:
          description: No Content
    get:
      tags:
        - accounts
      summary: List accounts
      operationId: listAccounts
      parameters:
        - name: email
          in: query
          description: Email of account to return
          required: false
          schema:
            type: string
      responses:
        200:
          description: Return account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        400:
          description: Invalid email supplied
        401:
          description: Missing authentication
        403:
          description: User not authorized
#      security:
#        - account_auth:
#            - admin
#            - platform
    post:
      tags:
        - accounts
      summary: Insert a new account
      operationId: insertAccount
      requestBody:
        description: Account data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InsertAccountRequest'
        required: true
      responses:
        201:
          description: Account created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InsertAccountResponse'
        401:
          description: Missing authentication
        403:
          description: User not authorized
        405:
          description: Invalid input
#      security:
#        - account_auth:
#            - admin
#            - platform
      x-codegen-request-body-name: body
components:
  schemas:
    InsertAccountRequest:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        role:
          type: string
    InsertAccountResponse:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        role:
          type: string
    DeleteAccountResponse:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
    ListAccountsResponse:
      type: array
      items:
        type: string
        format: uuid
    Account:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        name:
          type: string
        role:
          type: string
#  securitySchemes:
#    account_auth:
#      type: oauth2
#      flows:
#        implicit:
#          authorizationUrl: https://localhost:8081/auth/signin
#          scopes:
#            anonymous: user not logged
#            admin: user logged as admin
#            guest: user logged as guest
#            platform: platform token
