{{- $fullname := include "service.fullname" . -}}
{{- $name := include "service.name" . -}}
{{- $chart := include "service.chart" . -}}
{{- $root := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ $root.Values.configName | default "consul" }}.{{ $root.Release.Revision | default "1" }}'
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
data:
  config.json: |
    {
      "log_level": "info",
      "client_addr": "0.0.0.0",
      "bind_addr": "0.0.0.0",
      "server": true,
      "bootstrap": true,
      "leave_on_terminate": true,
      "translate_wan_addrs": true,
      "disable_update_check": true,
      "enable_script_checks": true,
      "skip_leave_on_interrupt": true,
      "ports": { "https": -1, "http": 8500 },
      "dns_config": {
        "allow_stale": true,
        "max_stale": "1s",
        "service_ttl": {
          "*": "5s"
        }
      },
      "services": [{
        "name": "server",
        "tags": [
          "http-endpoint"
        ],
        "port": {{ $root.Values.servicePort | default "443" }},
        "address": {{ $root.Values.serviceName | default "localhost" | quote }}
      }],
      "ui_config": {
        "enabled": true
      }
    }
