{{- $fullname := include "service.fullname" . -}}
{{- $name := include "service.name" . -}}
{{- $chart := include "service.chart" . -}}
{{- $root := . }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ $root.Values.secretName | default "mysql" }}.{{ $root.Release.Revision | default "1" }}'
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
data:
  MYSQL_ROOT_PASSWORD: {{ $root.Values.mysqlRootPassword | default "password" }}
  init.sql: |
    CREATE DATABASE IF NOT EXISTS {{ $root.Values.databaseName | default "accounts" }};

    CREATE USER IF NOT EXISTS admin IDENTIFIED BY '{{ $root.Values.adminPassword | default "password" }}' PASSWORD EXPIRE NEVER;
    CREATE USER IF NOT EXISTS verticle IDENTIFIED BY '{{ $root.Values.verticlePassword | default "password" }}' PASSWORD EXPIRE NEVER;
    GRANT SELECT, INSERT, UPDATE, DELETE ON {{ $root.Values.databaseName | default "accounts" }}.* TO admin;
    GRANT SELECT, INSERT, UPDATE, DELETE ON {{ $root.Values.databaseName | default "accounts" }}.* TO verticle;

    USE {{ $root.Values.databaseName | default "accounts" }};

    CREATE TABLE IF NOT EXISTS ACCOUNT (
      ACCOUNT_UUID VARCHAR(36) PRIMARY KEY,
      ACCOUNT_NAME VARCHAR(1024) NOT NULL,
      ACCOUNT_EMAIL VARCHAR(1024) NOT NULL,
      ACCOUNT_AUTHORITIES VARCHAR(128) NOT NULL,
      ACCOUNT_CREATED TIMESTAMP NOT NULL
    );

    FLUSH PRIVILEGES;
