{{- $fullname := include "service.fullname" . -}}
{{- $name := include "service.name" . -}}
{{- $chart := include "service.chart" . -}}
{{- $root := . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Values.name | default "kafka" }}
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    app: {{ $root.Values.name | default "kafka" | quote }}
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: broker
      protocol: TCP
      name: broker
    - port: 9094
      targetPort: broker-platform
      protocol: TCP
      name: broker-platform
  selector:
    app: {{ $root.Values.name | default "kafka" | quote }}
