{{- $fullname := include "service.fullname" . -}}
{{- $name := include "service.name" . -}}
{{- $chart := include "service.chart" . -}}
{{- $root := . }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ $root.Values.secretName | default "pactbroker" }}.{{ $root.Release.Revision | default "1" }}'
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
type: Opaque
stringData:
  PACT_BROKER_DATABASE_USERNAME: {{ $root.Values.pactbrokerUser | default "pactbrokeruser" }}
  PACT_BROKER_DATABASE_PASSWORD: {{ $root.Values.pactbrokerPassword | default "password" }}
