version: '3.4'
services:
  shop-designs-processor:
    labels:
        service: shop-designs-processor
    image: ${SHOP_DESIGNS_PROCESSOR_IMAGE}
    volumes:
      - storage:/data
    logging:
      options:
        labels: "service"
    ports:
      - target: 43011
        published: 43011
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.public == false
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 2048M
        reservations:
          cpus: '0.1'
          memory: 256M
    secrets:
      - source: server_conf
        target: /config/designs-processor.json
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: keystore_auth
        target: /keystores/keystore-auth.jceks
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: keystore_server
        target: /keystores/keystore-server.jks
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: kafka_keystore_client
        target: /keystores/kafka-keystore-client.jks
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: kafka_truststore_client
        target: /keystores/kafka-truststore-client.jks
        uid: '1000'
        gid: '1000'
        mode: 0440
networks:
  default:
    external:
      name: services
volumes:
    storage:
secrets:
  server_conf:
    file: ${ENVIRONMENT_SECRETS_PATH}/config/designs-processor.json
  keystore_auth:
    file: ${ENVIRONMENT_SECRETS_PATH}/keystores/keystore-auth.jceks
  keystore_server:
    file: ${ENVIRONMENT_SECRETS_PATH}/keystores/keystore-server.jks
  kafka_keystore_client:
    file: ${ENVIRONMENT_SECRETS_PATH}/kafka/keystore-client.jks
  kafka_truststore_client:
    file: ${ENVIRONMENT_SECRETS_PATH}/kafka/truststore-client.jks
