version: '3.4'
services:
  mysql:
    labels:
        service: shop-mysql
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - storage:/var/lib/mysql
    ports:
      - target: 43306
        published: 43306
        protocol: tcp
        mode: ingress
    logging:
      options:
        labels: "service"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.labels.zone == a
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 512M
networks:
  default:
    external:
      name: services
volumes:
    storage:
