version: '3.4'
services:
  consul-worker-ext1:
      labels:
          service: consul-agent
      image: ${CONSUL_IMAGE}
      command: "consul agent -node=worker-ext1 -data-dir=/consul/data -config-dir=/consul/config -client='0.0.0.0' -bind='0.0.0.0' -advertise='${ADVERTISE_EXT_WORKER_AGENT_1}' --retry-join=consul1 --retry-join=consul2 --retry-join=consul3"
      logging:
        options:
          labels: "service"
      ports:
        - target: 8301
          published: 8301
          protocol: tcp
          mode: host
        - target: 8301
          published: 8301
          protocol: udp
          mode: host
      deploy:
        mode: global
        placement:
          constraints:
            - node.role == worker
            - node.labels.public == true
            - node.labels.zone == a
        endpoint_mode: dnsrr
        update_config:
          parallelism: 1
          failure_action: rollback
          delay: 30s
        restart_policy:
          condition: any
          delay: 5s
          window: 120s
        resources:
          limits:
            cpus: '1'
            memory: 128M
          reservations:
            cpus: '0.1'
            memory: 128M
      secrets:
        - source: server_cert
          target: /consul/config/server_cert.pem
          uid: '100'
          gid: '1000'
          mode: 0440
      configs:
        - source: consul_config_a
          target: /consul/config/consul.json
          uid: '100'
          gid: '1000'
          mode: 0440
  consul-worker-ext2:
    labels:
        service: consul-agent
    image: ${CONSUL_IMAGE}
    command: "consul agent -node=worker-ext2 -data-dir=/consul/data -config-dir=/consul/config -client='0.0.0.0' -bind='0.0.0.0' -advertise='${ADVERTISE_EXT_WORKER_AGENT_2}' --retry-join=consul1 --retry-join=consul2 --retry-join=consul3"
    logging:
      options:
        labels: "service"
    ports:
      - target: 8301
        published: 8301
        protocol: tcp
        mode: host
      - target: 8301
        published: 8301
        protocol: udp
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.labels.public == true
          - node.labels.zone == b
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 128M
    secrets:
      - source: server_cert
        target: /consul/config/server_cert.pem
        uid: '100'
        gid: '1000'
        mode: 0440
    configs:
      - source: consul_config_b
        target: /consul/config/consul.json
        uid: '100'
        gid: '1000'
        mode: 0440
  consul-worker-ext3:
    labels:
        service: consul-agent
    image: ${CONSUL_IMAGE}
    command: "consul agent -node=worker-ext3 -data-dir=/consul/data -config-dir=/consul/config -client='0.0.0.0' -bind='0.0.0.0' -advertise='${ADVERTISE_EXT_WORKER_AGENT_3}' --retry-join=consul1 --retry-join=consul2 --retry-join=consul3"
    logging:
      options:
        labels: "service"
    ports:
      - target: 8301
        published: 8301
        protocol: tcp
        mode: host
      - target: 8301
        published: 8301
        protocol: udp
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.labels.public == true
          - node.labels.zone == c
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 128M
    secrets:
      - source: server_cert
        target: /consul/config/server_cert.pem
        uid: '100'
        gid: '1000'
        mode: 0440
    configs:
      - source: consul_config_c
        target: /consul/config/consul.json
        uid: '100'
        gid: '1000'
        mode: 0440
networks:
  default:
    external:
      name: services
secrets:
  server_cert:
    file: ${ENVIRONMENT_SECRETS_PATH}/consul/server_cert.pem
configs:
  consul_config_a:
    file: ${ENVIRONMENT_SECRETS_PATH}/config/consul-a.json
  consul_config_b:
    file: ${ENVIRONMENT_SECRETS_PATH}/config/consul-b.json
  consul_config_c:
    file: ${ENVIRONMENT_SECRETS_PATH}/config/consul-c.json
