version: '3.8'
services:
  nexus:
    restart: on-failure
    image: sonatype/nexus3:latest
    environment:
      NEXUS_CONTEXT: "/"
      INSTALL4J_ADD_VM_PARAMS: "-Xms2g -Xmx2g -XX:MaxDirectMemorySize=3g -Djava.util.prefs.userRoot=/nexus-data/javaPrefs"
    ports:
      - target: 8081
        published: 38081
        protocol: tcp
        mode: host
    networks:
      - platform
    volumes:
      - nexus-data:/nexus-data
volumes:
  nexus-data:
networks:
  platform:
    driver: bridge
