version: '3.8'
services:
  nexus:
    restart: unless-stopped
    image: sonatype/nexus3:3.37.3
    environment:
      NEXUS_CONTEXT: "/"
      INSTALL4J_ADD_VM_PARAMS: "-Xms2g -Xmx2g -XX:MaxDirectMemorySize=2g -Djava.util.prefs.userRoot=/nexus/data/javaPrefs"
    ports:
      - target: 8081
        published: 8082
        protocol: tcp
        mode: host
    networks:
      - bridge
    volumes:
      - nexus-data:/nexus/data
  pact-server:
    restart: unless-stopped
    image: pactfoundation/pact-broker:2.79.0.1
    environment:
      PACT_BROKER_DATABASE_USERNAME: 'pactbrokeruser'
      PACT_BROKER_DATABASE_PASSWORD: 'password'
      PACT_BROKER_DATABASE_HOST: 'postgres'
      PACT_BROKER_DATABASE_NAME: 'pactbroker'
    ports:
      - target: 9292
        published: 9292
        protocol: tcp
        mode: host
    networks:
      - bridge
  postgres:
    restart: unless-stopped
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    networks:
      - bridge
    volumes:
      - ./scripts/pactbrocker.sql:/docker-entrypoint-initdb.d/pactbrocker.sql:ro
      - postgres-data:/var/lib/postgresql/data/pgdata
volumes:
  nexus-data:
  postgres-data:
networks:
  bridge:
    driver: bridge
