version: '3.8'
services:
  pact-server:
    restart: on-failure
    image: pactfoundation/pact-broker:2.79.0.1
    environment:
      PACT_BROKER_DATABASE_USERNAME: 'pactbrokeruser'
      PACT_BROKER_DATABASE_PASSWORD: 'password'
      PACT_BROKER_DATABASE_HOST: 'postgres'
      PACT_BROKER_DATABASE_NAME: 'pactbroker'
    ports:
      - target: 9292
        published: 9292
        protocol: tcp
        mode: host
      - 20000-20010:20000-20010/tcp
    networks:
      - platform
  postgres:
    restart: on-failure
    image: postgres:9.6.21-alpine
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    networks:
      - platform
    volumes:
      - /scripts/pactbrocker.sql:/docker-entrypoint-initdb.d/pactbrocker.sql
      - pact-data:/var/lib/postgresql/data/pgdata
volumes:
  pact-data:
networks:
  platform:
    driver: bridge
