version: '3.7'
services:
  mysql:
    restart: on-failure
    image: mysql:8.0.13
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    networks:
      - platform
    volumes:
      - /scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  cassandra:
    restart: on-failure
    image: nextbreakpoint/cassandra:3.11.10-1
    environment:
      CASSANDRA_DC: 'DC1'
      CASSANDRA_RACK: 'RACK1'
      JVM_OPTS: '-Xms2G -Xmx2G'
    ports:
      - target: 9042
        published: 9042
        protocol: tcp
        mode: host
    networks:
      - platform
    volumes:
      - /scripts/init.cql:/docker-entrypoint-initdb.d/init.cql
  zookeeper:
    restart: on-failure
    image: nextbreakpoint/zookeeper:3.6.2-1
    environment:
      ZOO_MY_ID: '1'
    ports:
      - target: 2181
        published: 2181
        protocol: tcp
        mode: host
    networks:
      - platform
  kafka:
    restart: on-failure
    image: nextbreakpoint/kafka:6.1.0-1
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_EXTERNAL://192.168.64.12:9093,PLAINTEXT_INTERNAL://kafka:9092'
      KAFKA_LISTENERS: 'PLAINTEXT_EXTERNAL://0.0.0.0:9093,PLAINTEXT_INTERNAL://0.0.0.0:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT_EXTERNAL:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT_INTERNAL'
      KAFKA_BROKER_ID: '1'
      KAFKA_BROKER_RACK: 'rack1'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_NUM_PARTITIONS: '16'
      KAFKA_DELETE_TOPICS: 'true'
      KAFKA_AUTO_CREATE_TOPICS: 'true'
      KAFKA_LOG_RETENTION_HOURS: '24'
      KAFKA_TRANSACTION_MAX_TIMEOUT_MS: '60000'
      KAFKA_HEAP_OPTS: '-Xms1500M -Xmx1500M'
      CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
      - target: 9093
        published: 9093
        protocol: tcp
        mode: host
    networks:
      - platform
  consul:
    restart: on-failure
    image: consul:1.9.4
    command:
      - consul
      - agent
      - -data-dir=/consul/data
      - -config-dir=/consul/config
    ports:
      - target: 8300
        published: 8300
        protocol: tcp
        mode: host
      - target: 8301
        published: 8301
        protocol: tcp
        mode: host
      - target: 8302
        published: 8302
        protocol: tcp
        mode: host
      - target: 8400
        published: 8400
        protocol: tcp
        mode: host
      - target: 8600
        published: 8600
        protocol: tcp
        mode: host
    networks:
      - platform
    volumes:
      - /scripts/consul.json:/consul/config/config.json
#  nginx:
#    restart: on-failure
#    image: nginx:1.18.0-alpine
#    ports:
#      - target: 80
#        published: 80
#        protocol: tcp
#        mode: host
#      - target: 443
#        published: 443
#        protocol: tcp
#        mode: host
#    networks:
#      - platform
#    volumes:
#      - /scripts/nginx.conf:/etc/nginx/nginx.conf
#      - /secrets/nginx_server_key.pem:/etc/nginx/server_key.pem
#      - /secrets/nginx_server_cert.pem:/etc/nginx/server_cert.pem
  elasticsearch:
    restart: on-failure
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      discovery.type: single-node
      # xpack.security.enabled: 'false'
      ES_JAVA_OPTS: '-Xms2G -Xmx2G'
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
      - target: 9300
        published: 9300
        protocol: tcp
        mode: host
    networks:
      - platform
  kibana:
    restart: on-failure
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    ports:
      - target: 5601
        published: 5601
        protocol: tcp
        mode: host
    networks:
      - platform
  jaeger:
    restart: on-failure
    image: jaegertracing/all-in-one:1.22
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elasticsearch:9200
      ES_TAGS_AS_FIELDS_ALL: 'true'
    ports:
      - target: 16686
        published: 16686
        protocol: tcp
        mode: host
      - target: 5775
        published: 5775
        protocol: udp
        mode: host
      - target: 5778
        published: 5778
        protocol: tcp
        mode: host
      - target: 6831
        published: 6831
        protocol: udp
        mode: host
      - target: 6832
        published: 6832
        protocol: udp
        mode: host
      - target: 14250
        published: 14250
        protocol: tcp
        mode: host
      - target: 14268
        published: 14268
        protocol: tcp
        mode: host
    networks:
      - platform
volumes:
  data:
networks:
  platform:
    driver: bridge
