{{- $fullname := include "service.fullname" . -}}
{{- $name := include "service.name" . -}}
{{- $chart := include "service.chart" . -}}
{{- $root := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ $root.Values.configName | default "frontend" }}.{{ $root.Release.Revision | default "1" }}'
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
data:
  config.json: |
    {
      "client_web_url": {{ $root.Values.clientWebUrl | quote }},
      "client_api_url": {{ $root.Values.clientApiUrl | quote }},
      "server_api_url": {{ $root.Values.serverApiUrl | default "http://nginx.platform.svc.cluster.local:8000" | quote }}
    }