DROP DATABASE IF EXISTS accounts;

CREATE DATABASE accounts;

USE accounts;

CREATE TABLE IF NOT EXISTS ACCOUNTS (UUID VARCHAR(36) PRIMARY KEY, NAME VARCHAR(1024) NOT NULL, EMAIL VARCHAR(1024) NOT NULL, ROLE VARCHAR(128) NOT NULL);

CREATE USER IF NOT EXISTS verticle IDENTIFIED BY 'password' PASSWORD EXPIRE NEVER;

GRANT SELECT, INSERT, UPDATE, DELETE ON accounts.* TO verticle;

FLUSH PRIVILEGES;
