# Default values.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: nextbreakpoint/cassandra
  tag: 3.11.16-1
  pullPolicy: IfNotPresent
  pullSecrets:

annotations:

strategy:
  type: Recreate

resources:
  requests:
    memory: "2500Mi"
    cpu: "0.1"
  limits:
    memory: "2500Mi"
    cpu: "1.0"

serviceAccount: default
