apiVersion: v1
kind: Service
metadata:
  name: nginx-server
  namespace: default
  labels:
    app: nginx
spec:
  ports:
    - port: 443
      nodePort: 32443
      name: ngnix-ssl
    - port: 80
      nodePort: 32080
      name: ngnix
  selector:
    app: nginx
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-server
  namespace: default
  labels:
    app: nginx
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      name: nginx-server
      namespace: default
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx-server
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx
          readOnly: true
      volumes:
      - name: nginx-config
        secret:
          secretName: nginx-config
