apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-server
  namespace: default
  labels:
    app: mysql
spec:
  storageClassName: standard
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv-1
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  namespace: default
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      nodePort: 32306
      name: mysql
  selector:
    app: mysql
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-server
  namespace: default
  labels:
    app: mysql
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      name: mysql-server
      namespace: default
      labels:
        app: mysql
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - image: mysql:latest
        name: mysql-server
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password.txt
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-scripts
          mountPath: /scripts
          readOnly: true
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-server
      - name: mysql-scripts
        secret:
          secretName: mysql-scripts
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-server
  namespace: default
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      app: "mysql"