# Default values.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: nextbreakpoint/zookeeper
  tag: 3.9.1-1
  pullPolicy: IfNotPresent
  pullSecrets:

annotations:

strategy:
  type: Recreate

resources:
  requests:
    memory: "1024Mi"
    cpu: "0.1"
  limits:
    memory: "1024Mi"
    cpu: "1.0"

serviceAccount: default

