image:
  tag: 1.9.0

config:
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*platform*.log
        Multiline.parser docker, cri
        Tag kube.platform.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name tail
        Path /var/log/containers/*services*.log
        Multiline.parser docker, cri
        Tag kube.services.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

  filters: |
    [FILTER]
        Name kubernetes
        Match kube.platform.*
        Kube_Tag_Prefix kube.platform.var.log.containers.
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [FILTER]
        Name kubernetes
        Match kube.services.*
        Kube_Tag_Prefix kube.services.var.log.containers.
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host elasticsearch
        Port 9200
        Replace_Dots On
        Logstash_Format On
        Retry_Limit false
        Trace_Error Off
        Log_Level info

    [OUTPUT]
        Name es
        Match host.*
        Host elasticsearch
        Port 9200
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False
        Trace_Error Off
        Log_Level info
