{
 "title": "Platform Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "container", "query": { "query": "jvm_memory_max_bytes" } }
  ]
 },
 "panels": [
  {
   "title": "Node Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(1 - node_filesystem_free_bytes / node_filesystem_size_bytes) by (device, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(1 - node_memory_MemFree_bytes / node_memory_MemTotal_bytes) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"services\", container=~\"[[container]]\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=\"services\", container=~\"[[container]]\"}[5m])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Resource Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"services\", container=~\"[[container]]\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Resource Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"services\", container=~\"[[container]]\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(system_cpu_count{namespace=\"services\", container=~\"[[container]]\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(system_cpu_usage{namespace=\"services\", container=~\"[[container]]\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (container) (jvm_memory_used_bytes{namespace=\"services\", container=~\"[[container]]\"}) / sum by (container) (jvm_memory_max_bytes{namespace=\"services\", container=~\"[[container]]\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Live Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (container) (jvm_threads_live_threads{namespace=\"services\", container=~\"[[container]]\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM GC Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (container) (jvm_gc_live_data_size_bytes{namespace=\"services\", container=~\"[[container]]\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, container) (rate(jvm_gc_pause_seconds_bucket{namespace=\"services\", container=~\"[[container]]\"}[5m])))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Server Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (container) (rate(vertx_http_server_requests_total{namespace=\"services\", container=~\"[[container]]\"}[5m]))",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Client Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (container) (rate(vertx_http_client_requests_total{namespace=\"services\", container=~\"[[container]]\"}[5m]))",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Kafka Polling Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "records" } },
   "targets": [
    {
     "expr": "sum by (container, group_id, error) (rate(kafka_polling_error_count_total{namespace=\"services\", container=~\"[[container]]\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Polling Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "records" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, container, group_id) (rate(kafka_polling_queue_size_bucket{namespace=\"services\", container=~\"[[container]]\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Polling Process Records Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, container, group_id) (rate(kafka_polling_process_records_time_seconds_bucket{namespace=\"services\", container=~\"[[container]]\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Polling Consume Records Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, container, group_id) (rate(kafka_polling_consume_records_time_seconds_bucket{namespace=\"services\", container=~\"[[container]]\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Polling Queue Add Record",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (container, group_id) (rate(kafka_polling_queue_add_record_count_total{namespace=\"services\", container=~\"[[container]]\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Polling Queue Delete Record",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (container, group_id) (rate(kafka_polling_queue_delete_record_count_total{namespace=\"services\", container=~\"[[container]]\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Polling Suspend Partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (container, group_id) (rate(kafka_polling_suspend_partition_count_total{namespace=\"services\", container=~\"[[container]]\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Polling Resume Partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (container, group_id) (rate(kafka_polling_resume_partition_count_total{namespace=\"services\", container=~\"[[container]]\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Emitter Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (rate(kafka_emitter_error_count_total{namespace=\"services\", container=~\"[[container]]\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Consumer Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (rate(kafka_consumer_error_count_total{namespace=\"services\", container=~\"[[container]]\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Emitter Record Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (container, topic, type) (rate(kafka_emitter_record_type_count_total{namespace=\"services\", container=~\"[[container]]\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Consumer Record Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (container, topic, type) (rate(kafka_consumer_record_type_count_total{namespace=\"services\", container=~\"[[container]]\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Consumer Record Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, container, topic, type) (rate(kafka_consumer_record_latency_seconds_bucket{namespace=\"services\", container=~\"[[container]]\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}