apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-datasource
  namespace: observability
  labels:
    grafana_datasource: "1"
data:
  prometheus-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: "Prometheus"
      type: prometheus
      url: http://prometheus-operated:9090/
      access: proxy
      isDefault: false
