apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: monitoring
spec:
  ingress:
    enabled: false
  strategy: production
  collector:
    maxReplicas: 5
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
#  collector:
#    options:
#      kafka:
#        producer:
#          topic: jaeger-spans
#          brokers: kafka.platform:9092
#  ingester:
#    options:
#      kafka:
#        consumer:
#          topic: jaeger-spans
#          brokers: kafka.platform:9092
#      ingester:
#        deadlockInterval: 5s
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch.monitoring:9200
    esIndexCleaner:
      enabled: true
      numberOfDays: 1
      schedule: "55 23 * * *"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jaeger-operator-in-monitoring
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: jaeger-operator
    namespace: monitoring
roleRef:
  kind: Role
  name: jaeger-operator
  apiGroup: rbac.authorization.k8s.io
