apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
  labels:
    component: minio-init
spec:
  template:
    spec:
      containers:
        - name: minio-init
          image: minio/mc:latest
#          command: ["sh", "-c", "mc alias set minio http://minio:9000 admin password && (mc rb --force minio/fractals || true) && mc mb minio/fractals"]
          command: ["sh", "-c", "mc alias set minio http://minio:9000 admin password && mc mb minio/fractals"]
      restartPolicy: Never
  backoffLimit: 4
