apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: designs-render
  namespace: services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: designs-render
  minReplicas: 1
  maxReplicas: 8
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 50
        periodSeconds: 10
      selectPolicy: Max
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 80
        periodSeconds: 10
      selectPolicy: Max
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
