openapi: 3.0.1
info:
  title: Designs Command Consumer API
  description: API contract of service Designs Command Consumer
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://localhost/v1
tags:
  - name: designs
    description: Everything about modifying designs
paths:
  /designs/{designId}:
    delete:
      tags:
        - designs
      summary: Delete a design
      operationId: deleteDesign
      parameters:
        - name: designId
          in: path
          description: uuid of design to delete
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Design deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteDesignResponse'
        400:
          description: Invalid uuid supplied
          content: {}
        401:
          description: Missing authentication
          content: {}
        403:
          description: User not authorized
          content: {}
#      security:
#        - design_auth:
#            - admin
    put:
      tags:
        - designs
      summary: Update a design
      operationId: updateDesign
      parameters:
        - name: designId
          in: path
          description: uuid of design to update
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Design data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDesignRequest'
        required: true
      responses:
        200:
          description: Design updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateDesignResponse'
        400:
          description: Invalid uuid supplied
          content: {}
        401:
          description: Missing authentication
          content: {}
        403:
          description: User not authorized
          content: {}
      x-codegen-request-body-name: body
  #      security:
  #        - design_auth:
  #            - admin
  /designs:
    post:
      tags:
        - designs
      summary: Insert a new design
      operationId: insertDesign
      requestBody:
        description: Design data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InsertDesignRequest'
        required: true
      responses:
        201:
          description: Design created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InsertDesignResponse'
        401:
          description: Missing authentication
          content: {}
        403:
          description: User not authorized
          content: {}
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
#      security:
#        - design_auth:
#            - admin
components:
  schemas:
    InsertDesignRequest:
      type: object
      properties:
        manifest:
          type: string
        metadata:
          type: string
        script:
          type: string
        levels:
          type: integer
    InsertDesignResponse:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
    UpdateDesignRequest:
      type: object
      properties:
        manifest:
          type: string
        metadata:
          type: string
        script:
          type: string
        levels:
          type: integer
    UpdateDesignResponse:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
    DeleteDesignResponse:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
#  securitySchemes:
#    design_auth:
#      type: oauth2
#      flows:
#        implicit:
#          authorizationUrl: https://localhost:8081/auth/signin
#          scopes:
#            anonymous: user not logged
#            admin: user logged as admin
#            guest: user logged as guest
#            platform: platform token
