apiVersion: v1
kind: Service
metadata:
  name: designs-service
  namespace: default
  labels:
    app: designs-service
spec:
  ports:
    - port: 3001
      name: designs-service
  selector:
    app: designs-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: designs-service
  namespace: default
  labels:
    app: designs-service
spec:
  template:
    metadata:
      name: designs-service
      namespace: default
      labels:
        app: designs-service
    spec:
      containers:
      - image: docker/designs-service:1.0.0
        name: designs-service
        volumeMounts:
        - name: designs-service-config
          mountPath: /config
          readOnly: true
        - name: keystores
          mountPath: /keystores
          readOnly: true
      volumes:
      - name: designs-service-config
        secret:
          secretName: designs-service-config
      - name: keystores
        secret:
          secretName: keystores
