apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: default
  labels:
    app: web-service
spec:
  ports:
    - port: 8080
      name: web-service
  selector:
    app: web-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-service
  namespace: default
  labels:
    app: web-service
spec:
  template:
    metadata:
      name: web-service
      namespace: default
      labels:
        app: web-service
    spec:
      containers:
      - image: docker/web-service:1.0.0
        name: web-service
        volumeMounts:
        - name: web-service-config
          mountPath: /config
          readOnly: true
        - name: keystores
          mountPath: /keystores
          readOnly: true
      volumes:
      - name: web-service-config
        secret:
          secretName: web-service-config
      - name: keystores
        secret:
          secretName: keystores
