openapi: 3.0.1
info:
  title: Authentication API
  description: API contract of service Authentication
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost
tags:
  - name: authentication
    description: Everything about authentication
paths:
  /apidocs:
    get:
      operationId: apidocs
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /health:
    get:
      operationId: health
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /metrics:
    get:
      operationId: metrics
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /v1/auth/signin/*:
    options:
      operationId: signInOptions
      responses:
        204:
          description: No Content
    get:
      tags:
        - authentication
      summary: Signin user and redirect to landing page
      operationId: signIn
      responses:
        302:
          description: Redirect to authentication page
        303:
          description: User authenticated. Redirect to landing page
        400:
          description: Invalid authorization
        401:
          description: Missing authorization
        403:
          description: User not authorized
        405:
          description: Method not allowed
        500:
          description: Failed to authenticate user
  /v1/auth/signout/*:
    options:
      operationId: signOutOptions
      responses:
        204:
          description: No Content
    get:
      tags:
        - authentication
      summary: Signout user and redirect to landing page
      operationId: signOut
      responses:
        303:
          description: Redirect to landing page
  /v1/auth/callback:
    options:
      operationId: callbackOptions
      responses:
        204:
          description: No Content
    get:
      tags:
        - authentication
      summary: Callback
      operationId: callback
      responses:
        400:
          description: Invalid request
        401:
          description: Invalid token
        403:
          description: Insufficient scope
