openapi: 3.0.1
info:
  title: Authentication API
  description: API contract of service Authentication
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost/v1
tags:
  - name: authentication
    description: Everything about authentication
paths:
  /auth/signin/*:
    get:
      tags:
        - authentication
      summary: Signin user and redirect to landing page
      operationId: signIn
      responses:
        302:
          description: Redirect to authentication page
          content: {}
        303:
          description: User authenticated. Redirect to landing page
          content: {}
        400:
          description: Invalid authorization
          content: {}
        401:
          description: Missing authorization
          content: {}
        403:
          description: User not authorized
          content: {}
        405:
          description: Method not allowed
          content: {}
        500:
          description: Failed to authenticate user
          content: {}
  /auth/signout:
    get:
      tags:
        - authentication
      summary: Signout user and redirect to landing page
      operationId: signOut
      responses:
        303:
          description: Redirect to landing page
          content: {}
  /auth/callback/*:
    get:
      tags:
        - authentication
      summary: Callback
      operationId: callback
      responses:
        400:
          description: Invalid request
          content: {}
        401:
          description: Invalid token
          content: {}
        403:
          description: Insufficient scope
          content: {}
