DROP DATABASE IF EXISTS `accounts`;
CREATE DATABASE `accounts`;

DROP DATABASE IF EXISTS `designs`;
CREATE DATABASE `designs`;

CREATE USER IF NOT EXISTS 'liquibase' IDENTIFIED BY 'password' PASSWORD EXPIRE NEVER;
CREATE USER IF NOT EXISTS 'verticle' IDENTIFIED BY 'password' PASSWORD EXPIRE NEVER;

GRANT ALL ON `accounts`.* TO 'liquibase';
GRANT ALL ON `designs`.* TO 'liquibase';

GRANT SELECT, INSERT, UPDATE, DELETE ON `accounts`.* TO 'verticle';
GRANT SELECT, INSERT, UPDATE, DELETE ON `designs`.* TO 'verticle';

FLUSH PRIVILEGES;
