{{- $fullname := include "service.fullname" . -}}
{{- $name := include "service.name" . -}}
{{- $chart := include "service.chart" . -}}
{{- $root := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ $root.Values.configName | default "designs-command" }}.{{ $root.Release.Revision | default "1" }}'
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
data:
  config.json: |
    {
      "host_port": "8080",

      "jwt_keystore_path": "/etc/keystore_auth.jceks",
      "jwt_keystore_type": "jceks",
      "jwt_keystore_secret": "${KEYSTORE_SECRET}",

      "origin_pattern": "{{ $root.Values.clientProtocol | default "http" }}://{{ $root.Values.clientDomain | default "localhost" }}(:[0-9]+)?",

      "client_verify_host": "{{ $root.Values.clientVerifyHost | default "false" }}",
                        
      "server_designs_render_url": {{ $root.Values.designsRenderApiUrl | default "http://designs-render:8080" | quote }},

      "cassandra_cluster": {{ $root.Values.datacenter | default "datacenter1" | quote }},
      "cassandra_keyspace": {{ $root.Values.cassandraKeyspace | default "designs_command" | quote }},
      "cassandra_username": "${DATABASE_USERNAME}",
      "cassandra_password": "${DATABASE_PASSWORD}",
      "cassandra_contactPoints": {{ $root.Values.cassandraContactPoints | default "cassandra.platform" | quote }},
      "cassandra_port": {{ $root.Values.cassandraPort | default 9042 | quote }},

      "kafka_bootstrap_servers": {{ $root.Values.kafkaServers | default "kafka.platform:9094" | quote }},
      "schema_registry_url": {{ $root.Values.schemaRegistryUrl | default "http://schema-registry.platform:8081" | quote }},
      "kafka_group_id": {{ $root.Values.kafkaGroupId | default "designs-command" | quote }},
      "message_source": {{ $root.Values.messageSource | default "service-designs" | quote }},
      "commands_topic": {{ $root.Values.commandsTopic | default "commands" | quote }},
      "events_topic": {{ $root.Values.eventsTopic | default "events" | quote }}
    }