DROP DATABASE IF EXISTS designs;

CREATE DATABASE designs;

USE designs;

CREATE TABLE IF NOT EXISTS DESIGNS (UUID VARCHAR(36) PRIMARY KEY, JSON JSON NOT NULL, CREATED TIMESTAMP NOT NULL, UPDATED TIMESTAMP NOT NULL, CHECKSUM VARCHAR(100) NOT NULL);

CREATE USER IF NOT EXISTS verticle IDENTIFIED BY 'password' PASSWORD EXPIRE NEVER;

GRANT SELECT, INSERT, UPDATE, DELETE ON designs.* TO verticle;

FLUSH PRIVILEGES;
