# Default values for kafka.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: minio/minio
  tag: RELEASE.2024-01-01T16-36-33Z
  pullPolicy: IfNotPresent
  pullSecrets:

annotations:

strategy:
  type: Recreate

resources:
  requests:
    memory: "1024Mi"
    cpu: "0.1"
  limits:
    memory: "1024Mi"
    cpu: "1.0"

serviceAccount: default
