DROP DATABASE IF EXISTS accounts;
CREATE DATABASE accounts;

CREATE USER IF NOT EXISTS admin IDENTIFIED BY 'password' PASSWORD EXPIRE NEVER;
CREATE USER IF NOT EXISTS verticle IDENTIFIED BY 'password' PASSWORD EXPIRE NEVER;
GRANT SELECT, INSERT, UPDATE, DELETE ON accounts.* TO 'admin'@'%' WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON accounts.* TO 'verticle'@'%' WITH GRANT OPTION;

USE accounts;

CREATE TABLE IF NOT EXISTS ACCOUNT_ENTITY (
    ACCOUNT_UUID VARCHAR(36) PRIMARY KEY,
    ACCOUNT_NAME VARCHAR(1024) NOT NULL,
    ACCOUNT_EMAIL VARCHAR(1024) NOT NULL,
    ACCOUNT_AUTHORITIES VARCHAR(128) NOT NULL,
    ACCOUNT_CREATED TIMESTAMP NOT NULL
);

DROP DATABASE IF EXISTS designs;
CREATE DATABASE designs;

CREATE USER IF NOT EXISTS admin IDENTIFIED BY 'password' PASSWORD EXPIRE NEVER;
CREATE USER IF NOT EXISTS verticle IDENTIFIED BY 'password' PASSWORD EXPIRE NEVER;
GRANT SELECT, INSERT, UPDATE, DELETE ON designs.* TO 'admin'@'%' WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON designs.* TO 'verticle'@'%' WITH GRANT OPTION;

USE designs;

CREATE TABLE IF NOT EXISTS DESIGN_ENTITY (
    DESIGN_UUID VARCHAR(36) PRIMARY KEY,
    DESIGN_DATA JSON NOT NULL,
    DESIGN_CREATED TIMESTAMP NOT NULL,
    DESIGN_UPDATED TIMESTAMP NOT NULL,
    DESIGN_CHECKSUM VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS VERSION_ENTITY (
    VERSION_UUID VARCHAR(36) PRIMARY KEY,
    VERSION_CREATED TIMESTAMP NOT NULL,
    DESIGN_DATA JSON NOT NULL,
    DESIGN_CHECKSUM VARCHAR(100) NOT NULL
);

CREATE UNIQUE INDEX VERSION_CHECKSUM_IDX ON VERSION_ENTITY (DESIGN_CHECKSUM);

CREATE TABLE IF NOT EXISTS RENDER_ENTITY (
    RENDER_UUID VARCHAR(36) PRIMARY KEY,
    RENDER_LEVEL INTEGER(10) NOT NULL,
    RENDER_ERROR VARCHAR(64) NOT NULL,
    RENDER_STATUS VARCHAR(32) NOT NULL,
    RENDER_CREATED TIMESTAMP NOT NULL,
    RENDER_UPDATED TIMESTAMP NOT NULL,
    VERSION_UUID VARCHAR(36) NOT NULL
);

CREATE UNIQUE INDEX RENDER_VERSION_IDX ON RENDER_ENTITY (VERSION_UUID);

CREATE TABLE IF NOT EXISTS TILE_ENTITY (
    TILE_UUID VARCHAR(36) PRIMARY KEY,
    TILE_LEVEL INTEGER(10) NOT NULL,
    TILE_ERROR VARCHAR(64) NOT NULL,
    TILE_STATUS VARCHAR(32) NOT NULL,
    TILE_LOCATION VARCHAR(512) NOT NULL,
    TILE_CREATED TIMESTAMP NOT NULL,
    TILE_UPDATED TIMESTAMP NOT NULL,
    VERSION_UUID VARCHAR(36) NOT NULL
);

CREATE UNIQUE INDEX TILE_VERSION_LEVEL_IDX ON TILE_ENTITY (VERSION_UUID, TILE_LEVEL);

FLUSH PRIVILEGES;
